/*
 * This source file was generated by the Gradle 'init' task
 */
package com.akimbotheone.pg;

import com.akimbotheone.pg.patterns.behavioral.BehavioralPatternsDemo;
import com.akimbotheone.pg.patterns.creational.CreationalPatternsDemo;
import com.akimbotheone.pg.patterns.structural.StructuralPatternsDemo;

public class App {
    public String getGreeting() {
        return "Software Design Patterns Playground";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Running Complete Design Patterns Demo...\n");
        
        // Run all patterns demos
        CreationalPatternsDemo.main(args);
        StructuralPatternsDemo.main(args);
        BehavioralPatternsDemo.main(args);
        
        System.out.println("\n=== Complete Demo Finished ===");
    }
}
